### ISSUE TITLE
davix version 0.8.5 cannot authenticate using username and password with DAVIX_USE_LIBCURL

### ISSUE THREAD

**Issue by wxlg1117** [cern-fts/davix#109] opened 2023-11-15 16:19 UTC
```
[root@txhk2 ~]# export DAVIX_USE_LIBCURL=1
[root@txhk2 ~]# davix-ls --userlogin xxx --userpass xxx https://toi.teracloud.jp/dav/xxx-dat/ --debug
DAVIX(socket): ssl: Initialized OpenSSL thread-safety callbacks for 1 locks.

DAVIX(core): HTTP/SSL Session caching ENABLED
DAVIX(core): Redirection Session caching ENABLED
DAVIX(core): libdavix path /lib64/libdavix.so.0, version: 0.8.5
DAVIX(posix):  -> opendirpp
DAVIX(http): Create HttpRequest for https://toi.teracloud.jp/dav/xxx-dat/
DAVIX(http):  -> negotiateRequest
DAVIX(http): NEON start internal request
DAVIX(http): Failed to load certificate via callback: No valid client credential provided
DAVIX(http): Connection problem, retry
DAVIX(http):  -> negotiateRequest
DAVIX(http): NEON start internal request
DAVIX(http): Failed to load certificate via callback: No valid client credential provided
DAVIX(http): Connection problem, retry
DAVIX(http):  -> negotiateRequest
DAVIX(http): NEON start internal request
DAVIX(http): Failed to load certificate via callback: No valid client credential provided
DAVIX(http): Connection problem, retry
DAVIX(http):  -> negotiateRequest
DAVIX(http): NEON start internal request
DAVIX(http): Failed to load certificate via callback: No valid client credential provided
DAVIX(http): Connection problem: eradicate session
DAVIX(http):  <- negotiateRequest
DAVIX(http):  <- negotiateRequest
DAVIX(http):  <- negotiateRequest
DAVIX(http):  <- negotiateRequest
DAVIX(core): Destroy HttpRequest
DAVIX(posix):  <- opendirpp
(Davix::HttpRequest) Error: Failed to load certificate
[root@txhk2 ~]#
```

anybody can help ?

**Comment by mpatrascoiu** [comment] 2023-11-23 21:37
Hello,

This is the same problem as in https://github.com/cern-fts/davix/issues/81.

Since moving to `davix 0.8.0`, the username/password authentication was lost. The `libneon` backend could do this in the past, but we're hitting a regression. The `libcurl` backend misses the functionality altogether, so it has to be added. 

Current plans are to add it to the `libcurl` backend and then see what/if effort is available to bring it back for `libenon` as well.

Currently, you can work around the issue by creating the `Authorization: Basic` header manually:
```bash
$ davix-ls --debug -H "Authorization: Basic $(echo -n ${username}:${password} | base64 -w0)" <url>
```

Let's follow in the other ticket.

**Closed by mpatrascoiu** 2023-11-23 21:37 UTC
